name = "adabmp_fw"
description = ""
version = "0.1.0-dev"

authors = ["Greer Elias"]
maintainers = ["Greer Elias <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["main"]

[[pins]]
usb_embedded = { path = "./usb_embedded/"}

[[depends-on]]
pico_bsp = "^2.2.0"
usb_embedded = "*"
[build-switches]
"*".style_checks = "No"

[build-profiles]
usb_embedded = "development"